identidock:
  build: .
  expose:
    - "9090"
  environment:
    ENV: PROD
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis

dnmonster:
  image: amouat/dnmonster

redis:
  image: redis:3.0